### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by GaetanLepage** [google-deepmind/chex#313]
`chex` v0.1.83 is failing with the latest `jax` (0.4.19) as `jax.core.Shape`.
This issue has been fixed on the `master` branch of `chex` in [this commit](https://github.com/google-deepmind/chex/commit/70d13026b19ff21f00e2a6bc22ab594c450108b9).

Could you please make a release so as to ship this fix ?

Thank you very much !

**Comment by hbq1** [comment]
Done, thanks! https://github.com/google-deepmind/chex/releases/tag/v0.1.84

**Comment by GaetanLepage** [comment]
Thank you !
