### ISSUE TITLE
`jax.random.key` tree comparison results in a `ZeroDivision` warning

### ISSUE THREAD

**Issue by joeryjoery** [google-deepmind/chex#318]
See below:

```python
import jax
import chex

chex.assert_trees_all_equal(jax.random.key(0), jax.random.key(0))
> RuntimeWarning: divide by zero encountered in equal val = comparison(x, y)

# Runs fine
chex.assert_trees_all_equal(jax.random.PRNGKey(0), jax.random.PRNGKey(0))
```

The problem is not `jax` per se, since key comparison works:
```python
jax.random.key(0) == jax.random.key(1)
> Array(False, dtype=bool)

jax.random.key(0) == jax.random.key(0)
> Array(True, dtype=bool)
```

**Comment by joeryjoery** [comment]
Wanted to mention that the problem isn't chex per se, the problem is the `jax` random key not converting to a proper `numpy` type in the `numpy` test function.

Meaning, the problem is located in `np.testing.assert_allclose` where the jax type is converted using:
```python
np.asanyarray(jax.random.key(0))
> array(PRNGKeyArrayImpl[fry] { [0 0] }, dtype=object)

np.asanyarray(jax.random.PRNGKey(0))
> array([0, 0], dtype=uint32)
```

**Comment by hbq1** [comment]
Hi! Thanks for reporting. I don't think this should be handled in Chex since, as you correctly noticed, the warning arises in the Numpy <-> JAX interactions. 

Closing this issue for now.
