### ISSUE TITLE
Is my `reverse_cumsum` a good fit here?

### ISSUE THREAD

**Issue by cool-RR** [google-deepmind/chex#365]
Hi everyone. I wrote this simple function that I needed for my algorithm:

```
@functools.partial(jax.jit, static_argnames=('axis', 'dtype'))
def reverse_cumsum(a: jax.Array, axis: Optional[int] = None,
                   dtype: Optional[jax._src.typing.DTypeLike] = None,
                   out: None = None) -> jax.Array:
    return jax._src.numpy.reductions._cumulative_reduction(
        'reverse_cumsum', functools.partial(jax.lax.cumsum, reverse=True), a, axis, dtype, out
    )
```

I was thinking that maybe it belongs in some library for JAX-related tools. Do you think that Chex is a good place for it?

**Comment by jeertmans** [comment]
Hi @cool-RR, Chex is mostly a debug library, so I doubt this fits in this library (but I am not a maintainer of this, so I am just commenting).

If this is part of the NumPy API, but not JAX, then you can probably suggest that directly to the JAX repository.
